name: Post welcome comment
on:
  pull_request:
    types: [opened]       # fires only when a PR is opened :contentReference[oaicite:4]{index=4}
permissions:
  pull-requests: write    # allows comment creation :contentReference[oaicite:5]{index=5}
jobs:
  build:                  # every workflow must declare jobs :contentReference[oaicite:6]{index=6}
    name: Post welcome comment
    runs-on: ubuntu-latest  # cheapest hosted runner :contentReference[oaicite:7]{index=7}
    steps:
      - uses: actions/checkout@v4
      - name: Post welcome comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Welcome! Thanks for opening this pull request.
